### ISSUE TITLE
Add environment variable ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS (=3)

### ISSUE THREAD

**Issue by Rub3nC** [Rub3nC/python-auth-backend#4]
Determines the expiration date of email confirmation mails (# of days).

**Comment by Rub3nC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS (=3)](https://trello.com/c/j8A3faKA/2-accountemailconfirmationexpiredays-3)

**Comment by wilfredvasquez** [comment]
Done in this branch --> feature/add_email_confirme_expire
