### ISSUE TITLE
Encrypt passwords using bcrypt

### ISSUE THREAD

**Issue by Rub3nC** [Rub3nC/python-auth-backend#6]

**Comment by Rub3nC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Encrypt passwords using bcrypt](https://trello.com/c/SN1UGR4Y/4-encrypt-passwords-using-bcrypt)

**Comment by wilfredvasquez** [comment]
Done in this commit -> https://github.com/Rub3nC/python-auth-backend/commit/d281f17cebcd6f1ee74450cc39a40c0e219563de
