### ISSUE TITLE
Add base User model and EmailConfirmation models

### ISSUE THREAD

**Issue by Rub3nC** [Rub3nC/python-auth-backend#7]

**Comment by Rub3nC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add base User model and EmailConfirmation models](https://trello.com/c/IserY4T5/5-add-base-user-model-and-emailconfirmation-models)

**Comment by Rub3nC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add base User model and EmailConfirmation models](https://trello.com/c/IserY4T5/5-add-base-user-model-and-emailconfirmation-models)

**Comment by wilfredvasquez** [comment]
Done in this commit --> https://github.com/Rub3nC/python-auth-backend/commit/d281f17cebcd6f1ee74450cc39a40c0e219563de
